### ISSUE TITLE
Integrate React to work with Sass

### ISSUE THREAD

**Issue by puritybirir** [SpaceyaTech/team-helsinki-react#3]
Setup configuration to have the project run on Sass

**Comment by mamba-dev-KE** [comment]
Hey, assign this to me. Thanks.

**Comment by puritybirir** [comment]
Hey @mamba-dev-KE, assigned

**Comment by mamba-dev-KE** [comment]
Hey @puritybirir I saw that the PR is to be done to the develop branch, which currently does not exist.

**Comment by puritybirir** [comment]
Hey @mamba-dev-KE , make it to main for now
